### ISSUE TITLE
[QUESTION] Registry authentication

### ISSUE THREAD

**Issue by matyasrichter** [crazy-max/swarm-cronjob#151]
Hi,

thank you for your work on this project, it's been working perfectly for us.

We've come across an issue with pulling images from a private registry. While that's not specifically a swarm-cronjob issue, I was wondering if someone would be able to find a solution. When deploying with `docker stack deploy --with-registry-auth stackname`,   if the only service in the stack is a service to be run by swarm-cronjob, it naturally initially only scales to 0 replicas. However, this means that the image is not pulled immediately. So, when swarm-cronjob attempts to run the container later on (ie. the next day), the node doesn't have registry credentials available.

Has anyone experienced this issue? Is there a straightforward way of resolving it?

Any sort of help would be appreciated.

**Comment by jcrombez** [comment]
I'm having a similar issue and i have to thank you because you made me understand an understand why.

I knew i was having a private registry auth issue but it was random.
My stack has a "web" service and a "cron" service, both using the same image.
When our CI build a new image, we usually deploy the stack right after (and using `--with-registry-auth") but because we have an always running service (web) and it's replicated on the same nodes running the "cron" service, those nodes get to pull the image so everything works when the cron timing come.

But i'm having moment when the cron stop working because of the private registry auth missing.

And you made me realize it's most likely because sometime our CI build a new image but we don't deploy our stack until a few hours/days. In those rare cases, when Swarm want to run a cron i guess it sees (i'm not sure how it can without the auth...) the new image but can't pull it. Deploying seems to always fix crons so it would confirm this theory.

Anyway my "solution" for you would be to have a service with one replica, no restart policy and a dumb command to just run on deploy and die right away, in order to get your image pulled.

**Comment by matyasrichter** [comment]
I totally forgot about this issue! The solution is actually built into swarm-cronjob, and even documented. I must have missed it in the docs before I created this issue. You need to label the cronjob service (the actual end service, not swarm-cronjob itself) with `swarm.cronjob.registry-auth` as described [in the docs here](https://crazymax.dev/swarm-cronjob/usage/docker-labels/). When swarm cronjob launches the cronjob task (so, when it updates the service via the docker api), it extracts the credentials from the original one, as long as it's been deployed with `--with-registry-auth`.

My original workaround was exactly what you described - deploying a `global` dummy instance that would exit with 0 immediately, pulling the image to all nodes. That worked fine until we added a new node to our swarm. So I was happy to find out there's a solution for this already.

I'm closing this issue, hopefully the next person to overlook this information in the docs (like I did) will come across this :smile:
